version: "3.9"
services:
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_USER: khalil
      MYSQL_PASSWORD: khalil_pw
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/data/db

  api_service:
    image: "achat-app:latest"  
    restart: always
    ports:
      - 8089:8089
    networks:
      - springapimysql-net
    environment:
      SPRING_APPLICATION_JSON: '{"spring.datasource.url": "jdbc:mysql://mysqldb:3306/achatdb?allowPublicKeyRetrieval=true"}'
    stdin_open: true
    tty: true
    depends_on:
      - mysqldb
    volumes:
      - .:/achat-1.0

  achat-front:
    image: "achat-front:latest"  
    restart: always
    ports:
      - 4200:4200
    networks:
      - springapimysql-net

volumes:
  db:

networks:
  springapimysql-net:
    driver: bridge  
